# Generated by Django 4.2.5 on 2023-09-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messagetitle', models.CharField(max_length=100)),
                ('messagedescription', models.TextField(max_length=250)),
                ('image', models.ImageField(upload_to='about/')),
                ('whowearetitle', models.CharField(max_length=50)),
                ('businessnumber', models.CharField(max_length=20)),
                ('workers', models.CharField(max_length=100)),
                ('farmers', models.CharField(max_length=100)),
                ('whowearedescription', models.TextField(max_length=300)),
                ('historytitle', models.TextField(max_length=100)),
                ('historydescription', models.TextField(max_length=300)),
            ],
        ),
    ]
