# Generated by Django 4.2.5 on 2023-10-31 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_blog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
