# Generated by Django 4.2.5 on 2023-10-31 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_companies_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='description',
            field=models.CharField(max_length=1500),
        ),
    ]
