# Generated by Django 4.2.5 on 2023-10-31 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_companies_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='associations',
            old_name='link',
            new_name='name',
        ),
    ]
