# Generated by Django 4.2.5 on 2023-10-31 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_link_associations_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='testimonials/images/')),
                ('title', models.CharField(max_length=100)),
                ('matedescription', models.CharField(max_length=300)),
                ('postinCompany', models.CharField(max_length=100)),
            ],
        ),
    ]
