# Generated by Django 4.2.5 on 2023-10-31 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_testimonials'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonials',
            old_name='matedescription',
            new_name='description',
        ),
    ]
