# Generated by Django 4.2.5 on 2023-10-31 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_matedescription_testimonials_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Homepage',
            new_name='OurPatners',
        ),
    ]
