# Generated by Django 4.2.5 on 2023-10-31 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_homepage_ourpatners'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company_position', models.CharField(max_length=100)),
                ('short_description', models.TextField(blank=True)),
                ('twitter_link', models.CharField(max_length=100)),
                ('facebook_link', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='associations/')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomerReview',
        ),
    ]
