# Generated by Django 4.2.5 on 2023-10-31 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_teams_delete_customerreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='associations',
            old_name='name',
            new_name='link',
        ),
    ]
