# Generated by Django 4.2.5 on 2023-11-05 08:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_name_associations_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='whychoose',
            name='icon',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
